### ISSUE TITLE
[Request] Possible to have the counter in a different spot?

### ISSUE THREAD

**Issue by BeigeAnimal** [Strackeror/BeatSaberProgressCounter#4]
Would it be possible to make so the counter was on the left instead of the bottom? like in an earlier version of this plugin. I'm mainly asking because I love your plugin but a lot of Platforms I use don't take in account for your plugin so it gets covered up. So I have to choose between certain platforms and your plugin usually. I tired to compile the plugin myself with the other coordinates but I'm shit and have no idea what I'm doing.

**Comment by Strackeror** [comment]
Now possible in settings
