### ISSUE TITLE
[Request] Add this mod to the mod saber manager

### ISSUE THREAD

**Issue by Freeman015** [Strackeror/BeatSaberProgressCounter#7]
It seems that many users/streamers are using and loving your mod.
Is it an idea to register it for the mod saber manager so more it is easy to download and install.

( howto here: https://www.modsaber.ml/faq )

**Comment by Strackeror** [comment]
Done, https://www.modsaber.org/mod/progresscounter/4.0.0

**Comment by Freeman015** [comment]
awesome, thanks
